export const catalogo = [
  {
    id: 1,
    nombre: "Pomona Ring",
    precio: 240000,
    coleccionId: 1,
    descripcion:
      "Engastado a mano con un rubí de origen ético, terminado en nuestro taller de Lima.",
    material: "Oro 18k, rubí",
  },
  {
    id: 2,
    nombre: "Sillar Band",
    precio: 68000,
    coleccionId: 1,
    descripcion:
      "Una banda tallada inspirada en la piedra volcánica blanca de Arequipa.",
    material: "Plata de ley",
  },
  {
    id: 3,
    nombre: "Amaru Signet",
    precio: 129000,
    coleccionId: 1,
    descripcion:
      "Sello grabado con una serpiente, pulido a mano durante tres días.",
    material: "Baño de oro 18k",
  },
  {
    id: 4,
    nombre: "Quilla Solitaire",
    precio: 315000,
    coleccionId: 1,
    descripcion: "Un solo ópalo andino en un engaste bajo y discreto.",
    material: "Oro 18k, ópalo peruano",
  },
  {
    id: 5,
    nombre: "Inti Dome Ring",
    precio: 89000,
    coleccionId: 1,
    descripcion:
      "Un domo cepillado que atrapa la luz como el sol de la mañana.",
    material: "Plata de ley",
  },
  {
    id: 6,
    nombre: "Cordillera Stacking Ring",
    precio: 45000,
    coleccionId: 1,
    descripcion: "Estriado como una cordillera. Hecho para llevarse de a tres.",
    material: "Plata de ley",
  },
  {
    id: 7,
    nombre: "Ñusta Pendant",
    precio: 156000,
    coleccionId: 2,
    descripcion:
      "Una gota de crisocola en una cadena fina, tallada de una sola piedra.",
    material: "Baño de oro 18k, crisocola",
  },
  {
    id: 8,
    nombre: "Paracas Chain",
    precio: 98000,
    coleccionId: 2,
    descripcion:
      "Cada eslabón cerrado a mano. Queda justo debajo de la clavícula.",
    material: "Plata de ley",
  },
  {
    id: 9,
    nombre: "Chakana Locket",
    precio: 187000,
    coleccionId: 2,
    descripcion: "Una cruz andina grabada en un relicario que sí se abre.",
    material: "Oro 18k",
  },
  {
    id: 10,
    nombre: "Vicuña Collar",
    precio: 264000,
    coleccionId: 2,
    descripcion: "Un collar mate con el peso de algo que se guarda por años.",
    material: "Oro 18k",
  },
  {
    id: 11,
    nombre: "Luna Nueva Pendant",
    precio: 74000,
    coleccionId: 2,
    descripcion:
      "Una media luna delgada, lo bastante pequeña para dormir con ella.",
    material: "Plata de ley",
  },
  {
    id: 12,
    nombre: "Spondylus Strand",
    precio: 112000,
    coleccionId: 2,
    descripcion:
      "Concha spondylus comerciada en esta costa durante tres mil años.",
    material: "Spondylus, plata de ley",
  },
  {
    id: 13,
    nombre: "Killa Hoops",
    precio: 82000,
    coleccionId: 3,
    descripcion: "Aros de todos los días con el borde exterior martillado.",
    material: "Baño de oro 18k",
  },
  {
    id: 14,
    nombre: "Filigrana Drops",
    precio: 145000,
    coleccionId: 3,
    descripcion: "Filigrana tejida hilo por hilo en la tradición de Catacaos.",
    material: "Plata de ley",
  },
  {
    id: 15,
    nombre: "Catacaos Studs",
    precio: 56000,
    coleccionId: 3,
    descripcion: "El mismo trabajo de filigrana, reducido a un arete de botón.",
    material: "Baño de oro 18k",
  },
  {
    id: 16,
    nombre: "Nazca Drops",
    precio: 91000,
    coleccionId: 3,
    descripcion: "Una sola gota, pulida hasta que desaparecen las uniones.",
    material: "Oro 18k",
  },
  {
    id: 17,
    nombre: "Rodocrosita Studs",
    precio: 128000,
    coleccionId: 3,
    descripcion: "Rodocrosita, la piedra nacional, tallada en aretes redondos.",
    material: "Plata de ley, rodocrosita",
  },
  {
    id: 18,
    nombre: "Espiga Climbers",
    precio: 103000,
    coleccionId: 3,
    descripcion: "Trepadores con forma de espiga de trigo, pegados al lóbulo.",
    material: "Plata de ley",
  },
  {
    id: 19,
    nombre: "Cusco Cuff",
    precio: 172000,
    coleccionId: 4,
    descripcion: "Martillado a mano hasta que la superficie deja de ser plana.",
    material: "Plata de ley",
  },
  {
    id: 20,
    nombre: "Urubamba Bangle",
    precio: 94000,
    coleccionId: 4,
    descripcion: "Un aro liso con la curva de un valle de río.",
    material: "Baño de oro 18k",
  },
  {
    id: 21,
    nombre: "Trenza Bracelet",
    precio: 67000,
    coleccionId: 4,
    descripcion:
      "Tres hebras trenzadas como trenzaban el cabello nuestras abuelas.",
    material: "Plata de ley",
  },
  {
    id: 22,
    nombre: "Colca Chain Bracelet",
    precio: 138000,
    coleccionId: 4,
    descripcion: "Eslabones planos que se quedan quietos en la muñeca.",
    material: "Oro 18k",
  },
  {
    id: 23,
    nombre: "Q'ero Beaded Bracelet",
    precio: 52000,
    coleccionId: 4,
    descripcion:
      "Cuentas de spondylus ensartadas entre pequeños separadores de plata.",
    material: "Spondylus, plata de ley",
  },
  {
    id: 24,
    nombre: "Ayni Link Bracelet",
    precio: 209000,
    coleccionId: 4,
    descripcion:
      "Dos piedras de crisocola engastadas en un eslabón abierto y pesado.",
    material: "Oro 18k, crisocola",
  },
]
