export const catalogo = [
  {
    id: 1,
    nombre: "Pomona Ring",
    precio: 240000,
    coleccionId: 1,
    descripcion:
      "Hand-set with an ethically sourced ruby, finished in our Lima atelier.",
    material: "18k gold, ruby",
  },
  {
    id: 2,
    nombre: "Sillar Band",
    precio: 68000,
    coleccionId: 1,
    descripcion:
      "A carved band inspired by the white volcanic stone of Arequipa.",
    material: "Sterling silver",
  },
  {
    id: 3,
    nombre: "Amaru Signet",
    precio: 129000,
    coleccionId: 1,
    descripcion: "Engraved serpent signet, polished by hand over three days.",
    material: "18k gold vermeil",
  },
  {
    id: 4,
    nombre: "Quilla Solitaire",
    precio: 315000,
    coleccionId: 1,
    descripcion: "A single Andean opal held in a low, quiet setting.",
    material: "18k gold, Peruvian opal",
  },
  {
    id: 5,
    nombre: "Inti Dome Ring",
    precio: 89000,
    coleccionId: 1,
    descripcion: "A brushed dome that catches light the way morning sun does.",
    material: "Sterling silver",
  },
  {
    id: 6,
    nombre: "Cordillera Stacking Ring",
    precio: 45000,
    coleccionId: 1,
    descripcion: "Ridged like a mountain range. Made to be worn in threes.",
    material: "Sterling silver",
  },
  {
    id: 7,
    nombre: "Ñusta Pendant",
    precio: 156000,
    coleccionId: 2,
    descripcion: "A chrysocolla drop on a fine chain, cut from a single stone.",
    material: "18k gold vermeil, chrysocolla",
  },
  {
    id: 8,
    nombre: "Paracas Chain",
    precio: 98000,
    coleccionId: 2,
    descripcion: "Every link closed by hand. Sits just below the collarbone.",
    material: "Sterling silver",
  },
  {
    id: 9,
    nombre: "Chakana Locket",
    precio: 187000,
    coleccionId: 2,
    descripcion: "An Andean cross engraved on a locket that actually opens.",
    material: "18k gold",
  },
  {
    id: 10,
    nombre: "Vicuña Collar",
    precio: 264000,
    coleccionId: 2,
    descripcion: "A matte collar with the weight of something kept for years.",
    material: "18k gold",
  },
  {
    id: 11,
    nombre: "Luna Nueva Pendant",
    precio: 74000,
    coleccionId: 2,
    descripcion: "A thin crescent, small enough to sleep in.",
    material: "Sterling silver",
  },
  {
    id: 12,
    nombre: "Spondylus Strand",
    precio: 112000,
    coleccionId: 2,
    descripcion:
      "Spondylus shell traded along this coast for three thousand years.",
    material: "Spondylus, sterling silver",
  },
  {
    id: 13,
    nombre: "Killa Hoops",
    precio: 82000,
    coleccionId: 3,
    descripcion: "Everyday hoops with a hammered outer edge.",
    material: "18k gold vermeil",
  },
  {
    id: 14,
    nombre: "Filigrana Drops",
    precio: 145000,
    coleccionId: 3,
    descripcion: "Filigree woven thread by thread in the Catacaos tradition.",
    material: "Sterling silver",
  },
  {
    id: 15,
    nombre: "Catacaos Studs",
    precio: 56000,
    coleccionId: 3,
    descripcion: "The same filigree work, scaled down to a stud.",
    material: "18k gold vermeil",
  },
  {
    id: 16,
    nombre: "Nazca Drops",
    precio: 91000,
    coleccionId: 3,
    descripcion: "A single teardrop, polished until the seams disappear.",
    material: "18k gold",
  },
  {
    id: 17,
    nombre: "Rodocrosita Studs",
    precio: 128000,
    coleccionId: 3,
    descripcion: "Rhodochrosite, the national stone, cut into round studs.",
    material: "Sterling silver, rhodochrosite",
  },
  {
    id: 18,
    nombre: "Espiga Climbers",
    precio: 103000,
    coleccionId: 3,
    descripcion: "Climbers shaped after a wheat ear, worn close to the lobe.",
    material: "Sterling silver",
  },
  {
    id: 19,
    nombre: "Cusco Cuff",
    precio: 172000,
    coleccionId: 4,
    descripcion: "Hammered by hand until the surface stops being flat.",
    material: "Sterling silver",
  },
  {
    id: 20,
    nombre: "Urubamba Bangle",
    precio: 94000,
    coleccionId: 4,
    descripcion: "A smooth bangle with the bend of a river valley.",
    material: "18k gold vermeil",
  },
  {
    id: 21,
    nombre: "Trenza Bracelet",
    precio: 67000,
    coleccionId: 4,
    descripcion: "Three strands braided the way our grandmothers braided hair.",
    material: "Sterling silver",
  },
  {
    id: 22,
    nombre: "Colca Chain Bracelet",
    precio: 138000,
    coleccionId: 4,
    descripcion: "Flat links that lie still on the wrist.",
    material: "18k gold",
  },
  {
    id: 23,
    nombre: "Q'ero Beaded Bracelet",
    precio: 52000,
    coleccionId: 4,
    descripcion: "Spondylus beads strung between small silver spacers.",
    material: "Spondylus, sterling silver",
  },
  {
    id: 24,
    nombre: "Ayni Link Bracelet",
    precio: 209000,
    coleccionId: 4,
    descripcion: "Two chrysocolla stones set into a heavy open link.",
    material: "18k gold, chrysocolla",
  },
]
